### ISSUE TITLE
VAST OOMs when ingesting large pcaps

### ISSUE THREAD

**Issue by netantho** [tenzir/vast#2434] opened 2022-07-18 10:27 UTC
### Current Behavior

I'm ingesting pcaps of several GB with the command `vast import pcap < foo.pcap`

VAST uses several times a lot of RAM process the pcap (several times the size of the pcap itself).
My systems runs out of RAM and OOMs the `vast start` process.

### Expected Behavior

It would be useful if vast could stage data on disk when the memory is full. I have a NVMe disk so that's still acceptable performance wise.

### Steps To Reproduce

* Start VAST: `vast start`
* Generate a large pcap (tested on 5.5GB pcap) and import it with `vast import pcap < foo.pcap`.

### Environment

* Manjaro Linux (derived from Arch Linux)

```
$ uname -a
Linux manjaro 5.15.53-1-MANJARO #1 SMP PREEMPT Thu Jul 7 16:56:55 UTC 2022 x86_64 GNU/Linux
```

* VAST 2.1 with default config (apart from loading all open source model that comes by default with VAST)

**Comment by tobim** [comment] 2022-07-18 10:56
Hi @netantho. If I understand this report correctly we're actually looking at 2 problems here.

> VAST uses several times a lot of RAM process the pcap (several times the size of the pcap itself).

Interesting, I would expect it to be at most 2 times as large as the original.

> It would be useful if vast could stage data on disk when the memory is full. I have a NVMe disk so that's still acceptable performance wise.

Since VAST will eventually persist the data to disk anyways, I doubt a dedicated on-disk cache is the way to go, at least not as a general solution. I think your PCAP contains a few very big packets, which get stored in VAST as is. Unfortunately each packet corresponds to one event in VAST, and the cutoff mechanism for batches and partitions is based on the number of events or time, but not on the size of the data.

**Comment by netantho** [comment] 2022-07-18 22:38
I've been experimenting a bit more. Here are more details. Let me first say that I'm really impressed by VAST and I'm trying to push the limit of what it can do, so please don't see this as too negative.

The file sizes:
```
ls -lh --sort=size | head -10
total 87G
-rw-r--r-- 1 averez averez 5.5G Jul  4 10:02 capture_1650627932371758227.pcapng
-rw-r--r-- 1 averez averez 5.5G Jul  4 09:59 capture_1650627806936641132.pcapng
-rw-r--r-- 1 averez averez 5.3G Jul  4 10:02 capture_1650627958618166929.pcapng
-rw-r--r-- 1 averez averez 4.4G Jun 16 14:25 capture_1650627763449646486.pcapng
-rw-r--r-- 1 averez averez 4.3G Jul  4 10:00 capture_1650627870045585008.pcapng
-rw-r--r-- 1 averez averez 3.9G Apr 22 13:44 capture_1647267690253346727.pcapng
-rw-r--r-- 1 averez averez 2.5G Apr 22 13:45 capture_1647267751030829009.pcapng
-rw-r--r-- 1 averez averez 2.5G Apr 22 13:45 capture_1647267732853821462.pcapng
-rw-r--r-- 1 averez averez 2.2G Mar 14 15:21 capture_1645301953363280726.pcapng
```

I'm ingesting them in parallel:
```
parallel --gnu --bar -j 10 'vast import pcap < {}' ::: capture_1650627932371758227.pcapng capture_1650627806936641132.pcapng capture_1650627958618166929.pcapng capture_1650627763449646486.pcapng capture_1650627870045585008.pcapng capture_1647267690253346727.pcapng capture_1647267751030829009.pcapng capture_1647267732853821462.pcapng capture_1645301953363280726.pcapng
```

I observed that VAST keeps using the memory after `vast import pcap` succeeds. When only the last file is left to be processed (`vast import pcap < capture_1645301953363280726.pcapng`), `vast starts` gets OOMed. The machine I'm using has a total of 64GB of RAM and 69GB of swap. At that moment `vast start` was using ~45G of RAM and 69G of swap. When I rerun the batch import sometimes it passes without OOMing, about 50-50 chance.
When it does pass, the `vast start` process keeps using memory and swap for a while even after all the import commands have completed, without trying to dump things on disk (low/no disk write bandwith or write I/O usage). For about 15 secs no decrease of RAM or swap at all, then goes down to ~40G RAM and 27GB swap and stays like that for at least 15mins (I didn't wait more). When closing `vast start` gracefully I don't see disk usage either so I think the data was already on disk.

I don't think any particular  pcap was very problematic as I can successfully ingest them one by one on that powerful machine.

> > VAST uses several times a lot of RAM process the pcap (several times the size of the pcap itself).
> 
> Interesting, I would expect it to be at most 2 times as large as the original.

I'm seeing 2-3x times as the original. It can be a bit problematic in my case, with 5.5GB files. I can find cloud instances with cheap SSDs but cost grows linearly with amount of memory in my experience.

If I'm looking at a more powerful instance I'd then want to process several pcaps or remote clients in parallel.

> 
> > It would be useful if vast could stage data on disk when the memory is full. I have a NVMe disk so that's still acceptable performance wise.
> 
> Since VAST will eventually persist the data to disk anyways, I doubt a dedicated on-disk cache is the way to go, at least not as a general solution. I think your PCAP contains a few very big packets, which get stored in VAST as is. Unfortunately each packet corresponds to one event in VAST, and the cutoff mechanism for batches and partitions is based on the number of events or time, but not on the size of the data.

The pcaps are a bunch of very small packets, mostly just TCP sessions completing the handshake.

* Total packets in one of the big pcap: 23537943

```
==================================================================================================================================
Packet Lengths:
Topic / Item       Count         Average       Min Val       Max Val       Rate (ms)     Percent       Burst Rate    Burst Start  
----------------------------------------------------------------------------------------------------------------------------------
Packet Lengths     2182128       66.58         42            1946          0.0127        100%          2.0200        159650.152   
 0-19              0             -             -             -             0.0000        0.00%         -             -            
 20-39             0             -             -             -             0.0000        0.00%         -             -            
 40-79             1835494       56.41         42            79            0.0106        84.11%        2.0200        159650.152   
 80-159            332766        98.72         80            159           0.0019        15.25%        0.3200        8517.028     
 160-319           1552          211.98        160           319           0.0000        0.07%         0.0500        375.816      
 320-639           7525          475.51        321           622           0.0000        0.34%         1.2800        71213.612    
 640-1279          4760          1039.16       666           1274          0.0000        0.22%         0.0500        110158.076   
 1280-2559         31            1533.19       1389          1946          0.0000        0.00%         0.0200        60010.064    
 2560-5119         0             -             -             -             0.0000        0.00%         -             -            
 5120 and greater  0             -             -             -             0.0000        0.00%         -             -            

----------------------------------------------------------------------------------------------------------------------------------

```

> @netantho do you have multiple imports happening concurrently?

Yes. Otherwise it takes 4-5x more time to process 525 pcaps on the powerful machine.

> 
> > VAST uses several times a lot of RAM process the pcap (several times the size of the pcap itself).
> 
> A few more questions:
> 
> * By "several times", what are we roughly talking about? 2-3x?
> * How much RAM do you have available?
> * By "several GB", do you mean a value in the single digits, or something >10 GB?

Answered a bit higher.

> 
> There are several [tuning knobs](https://vast.io/docs/setup-vast/tune) that allow for adjusting the trade-off between latency (small batching) and throughput (large batches) on the ingest path.
> 
> It's hard to tell what needs to be adjusted exactly to reach a steady state in terms of memory usage, but it should be possible in theory. Since you are reading from file, the backpressure in the ingest pipeline should work out nicely and autotune the rate of reading packets.

Thanks, I will experiment a bit with that.

**Comment by tobim** [comment] 2022-07-19 14:47
Hey @netantho,

These OOMs are definitely unexpected at first glance. We will try to reproduce this based on the summary of the PCAP you provided. I'll look into this tomorrow.

**Comment by netantho** [comment] 2022-07-19 20:24
Thanks @tobim, no problem that's not really blocking me at this stage.

Note: I'll be far for the computer for the rest of the week, back on Monday. If you don't manage to easily reproduce I can share the pcaps privately with you and the team (or assist in other ways) when I'm back.

**Comment by tobim** [comment] 2022-07-21 23:07
I tried to reproduce this issue with a pcap of roughly the same size and ingesting the same data multiple times in parallel. Unfortunately I ran into an unrelated bug in v2.1 that has since been resolved on master and didn't get to repeat test yet.

> When only the last file is left to be processed (vast import pcap < capture_1645301953363280726.pcapng), vast starts gets OOMed. 

This is very curious. For now I'd say it is coincidence because `vast start` has no way to know that there is only one file left.

**Comment by netantho** [comment] 2022-07-27 10:55
I agree that it's probably a coincidence of this occurring on the last file.

It may be anecdotal but I've observed that at least in the case of the pcap plugin, VAST tends to use more RAM (>= ~3x the size of the pcap) when it's also using a lot of CPU time (typically on more dedicated and latest gen CPUs). I think it may not be limited to the pcap plugin as I've ran into OOMs on ingesting large Zeek `conn.log` files as well.

For example, I get a OOM when ingesting a 5.5G pcap (`capture_1650627932371758227.pcapng`) on a Hetzner CCX21 instance (16GB RAM, 160GB SSD, more specs at https://www.hetzner.com/cloud > Dedicated vCPU)


```
# cat /proc/cpuinfo

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel Xeon Processor (Skylake, IBRS)
stepping	: 4
microcode	: 0x1
cpu MHz		: 2099.998
cache size	: 16384 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm avx512f avx512dq rdseed adx smap clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat pku ospke md_clear
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit mmio_stale_data
bogomips	: 4199.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
```

My VAST build was from commit `9ac8ab1cdc29d4bb589b124fe70273546bf46bf3`

**Comment by dominiklohmann** [comment] 2022-07-28 07:55
@netantho Sorry for taking a while to get back to you.

> > > VAST uses several times a lot of RAM process the pcap (several times the size of the pcap itself).
> > 
> > 
> > Interesting, I would expect it to be at most 2 times as large as the original.
> 
> I'm seeing 2-3x times as the original. It can be a bit problematic in my case, with 5.5GB files. I can find cloud instances with cheap SSDs but cost grows linearly with amount of memory in my experience.

Let's differentiate between client (`vast import pcap`) and server (`vast start`) processes and talk about what's expected here:

For the client processes, we expect a peak of 2x the PCAP size in the worst case. This is because you have the PCAP in memory while you're reading it, and then you're converting that into Apache Arrow's Record Batches, which VAST uses as its underlying binary format. Before sending the record batches to the server process, we unconditionally compress them with Zstd. Once they're sent out the client processes no longer hold the batches in memory.

For the server process, we expect a peak of 2-3x the PCAP size, and I think this is where we can help you tune VAST to better match your expectations by explaining how the VAST server uses its memory.

VAST stores its data in partitions. A partition is effectively a concatenation of record batches of the same schema, a sparse index, and one dense index per field in the schema. VAST has active and passive partitions, with active partitions being always in memory and supporting reads and writes, and passive partitions being on disk and supporting only reads. When an active partition reaches a certain number of events (`vast.max-partition-size`, defaults to 4Mi), or when it reaches a certain timeout (`vast.active-partition-timeout`, defaults to 1h), we persist it to disk and turn it into a passive partition. Only then do we free the memory of all batches contained in the passive partition. A third variable that relates is how many passive partitions may be loaded for queries into memory at the same time (`vast.max-resident-partitions`, defaults to 10).

Your experience with everything being held in memory sounds or too many things being held in memory at the same time sounds like you want to play around with the relevant variables. Here's how you can do that:

```yaml
# vast.yaml configuration file: Install into either
# of these locations:
# - $PREFIX/etc/vast/vast.yaml
# - $HOME/.config/vast/vast.yaml

vast:
  # An upper bound for the number of events in newly 
  # created active partitions.
  max-partition-size: 4 Mi

  # The time after which to persist an active partition
  # regardless of its size.
  active-partition-timeout: 1 hour

  # An upper bound for the number of passive partitions
  # loaded into memory for queries.
  max-resident-partitions: 10

  # Additional, import process-related options.
  import:
    # An upper bound for the size of a single record
    # batch before sending it out to the server process.
    batch-size: 64 Ki

    # The time after which to cut a record batch
    # regardless of its size to send it out to the
    # server process. 
    batch-timeout: 10 seconds
```

There are some more options that I haven't shown here, and there's a full list in the vast.yaml.example file in the repository root, but to me it sounds like you want to rotate partitions earlier. The current defaults are tuned for large-scale deployments, and we should make that more explicit in the documentation.

If you ever change your mind about the partition size and want to rebuild existing undersized ones you can use the `vast rebuild` command to merge undersized partitions. One possible setup is to frequently rebuild undersized partitions when VAST idles, and setting a low `vast.active-partition-timeout` to remove the memory constraints (we want to automate this in the future and let this run automatically in the background).

Hope this helps you resolve the issue. If you feel stuck, please always feel free to ask here, check by in our [community Slack](http://slack.tenzir.com) or [schedule a meeting](https://calendly.com/dominiklohmann) with me directly. We're always happy to help—this is really important feedback to us.

**Comment by netantho** [comment] 2022-08-19 07:45
Follow up on this bug, thanks all for the stellar support on Slack! It think it's obsolete for my usage and feel free to close it.

Reasons:
- I discovered that when running several import jobs in parallel, I'm hitting a `request_timeout` bottleneck before hitting the RAM bottleneck, see https://github.com/tenzir/vast/pull/2503. I'm fine with the proposal in that PR to wait for the CAF 0.19 to be released and integrated in VAST, that would hopefully address the `request_timeout` bottleneck.
- I added RAM on my machine

**Comment by dominiklohmann** [comment] 2022-08-19 07:49
In addition to what you've said, we've also monitored a hefty reduction in RAM usage on our testbeds. From v2.2 to v2.3 with ~80k events/s we went down from 110 GB to 85 GB RAM on our largest setup, mostly due to the reduced `vast.active-partition-timeout` and automatic rebuilding.

This will kind of always be in-progress as something that we can continuously improve, so I agree with wanting to close this out.

**Closed by dominiklohmann** 2022-08-19 07:49 UTC
Labels: bug
